using System.Reflection;
using System.Text;

using GluLamb.Joints;

namespace GluLamb.Gallery
{
    /// <summary>
    /// The joint catalogue: README.md listing every registered joint type with its description,
    /// the conditions it is offered for (and where it is the default), its parameters, and a
    /// drawing of it on those conditions (the SVG each worker wrote next to it).
    /// </summary>
    internal static class Catalogue
    {
        public static void Write(string folder, List<JointTypeInfo> types, List<TypeRecord> records)
        {
            Directory.CreateDirectory(folder);
            var byId = records.ToDictionary(r => r.Id);

            var md = new StringBuilder();
            md.AppendLine("# Joint catalogue");
            md.AppendLine();
            md.AppendLine("Generated by GluLamb.Gallery from the joint registry; don't edit it by hand. Each joint type is tried on the gallery's");
            md.AppendLine("joint conditions, as drawn and with the beam sections turned a quarter turn, each with and without Flip. A cell passes");
            md.AppendLine("when the joint builds, no two cut beams overlap and every beam keeps its body. The drawings show each joint cropped");
            md.AppendLine("and pulled apart; beams are coloured by their order in the condition, hardware is grey.");
            md.AppendLine();
            md.AppendLine("| Type | Name | Conditions | Default for | Cells |");
            md.AppendLine("|---|---|---|---|---|");
            foreach (var type in types)
            {
                byId.TryGetValue(type.Id, out var r);
                var families = r == null ? "" : string.Join(", ", r.Offered.Select(x => x.Family).Distinct());
                var defaultFor = r == null ? "" : string.Join(", ", r.Offered.Where(x => x.Default).Select(x => x.Case));
                var result = r == null ? "no results" : r.Cells.Count == 0 ? "not tried" :
                    r.Cells.All(x => x.Pass) ? $"{r.Cells.Count} ok" : $"{r.Cells.Count(x => !x.Pass)} of {r.Cells.Count} fail";
                md.AppendLine($"| [`{type.Id}`](#{Anchor(type.Id)}) | {type.Name} | {families} | {defaultFor} | {result} |");
            }
            md.AppendLine();

            foreach (var type in types)
            {
                byId.TryGetValue(type.Id, out var r);

                md.AppendLine($"## {type.Id}");
                md.AppendLine();
                md.AppendLine($"**{type.Name}.** {type.Attribute.Description}");
                md.AppendLine();
                md.AppendLine($"Class `{type.Type.Name}`, {type.Attribute.Arity} part(s){(type.Attribute.Topology != JointTopology.Unknown ? $", {type.Attribute.Topology} topology" : "")}.");
                md.AppendLine();

                if (r != null && r.Offered.Count > 0)
                    md.AppendLine("Offered for: " + string.Join(", ", r.Offered.Select(x => x.Default ? $"**{x.Case}** (default)" : x.Case)) + ".");
                else
                    md.AppendLine("Not offered for any of the gallery's conditions.");
                md.AppendLine();

                if (type.Parameters.Count > 0)
                {
                    md.AppendLine("| Parameter | Default | Unit | Description |");
                    md.AppendLine("|---|---|---|---|");
                    foreach (var p in type.Parameters)
                    {
                        var attr = p.GetCustomAttribute<JointParameterAttribute>();
                        var value = r != null && r.Defaults.TryGetValue(p.Name, out var v) ? v : "";
                        if (attr?.Unit == "radians" && double.TryParse(value, System.Globalization.NumberStyles.Float, System.Globalization.CultureInfo.InvariantCulture, out var rad))
                            value = $"{Rhino.RhinoMath.ToDegrees(rad):0.##}°";
                        md.AppendLine($"| {p.Name} | {value} | {(attr?.Unit == "radians" ? "angle" : attr?.Unit)} | {attr?.Description?.Replace("|", "\\|")} |");
                    }
                    md.AppendLine();
                }

                if (r != null && r.Cells.Count > 0)
                {
                    md.AppendLine($"![{type.Name}]({type.Id}.svg)");
                    md.AppendLine();

                    foreach (var fail in r.Cells.Where(x => !x.Pass))
                        md.AppendLine($"- Fails on {fail.Case}, {fail.Variant}: {string.Join("; ", fail.Problems)}");
                    var messages = r.Cells.SelectMany(x => x.Messages).Distinct().ToList();
                    foreach (var m in messages)
                        md.AppendLine($"- Note: {m}");
                    if (r.Cells.Any(x => !x.Pass) || messages.Count > 0) md.AppendLine();
                }
            }

            File.WriteAllText(Path.Combine(folder, "README.md"), md.ToString());
        }

        private static string Anchor(string id) => id.Replace(".", "").ToLowerInvariant();
    }
}
