using System.Reflection;
using System.Text;

using GluLamb.Joints;

namespace GluLamb.Gallery
{
    /// <summary>
    /// The joint catalogue: README.md listing every registered joint type with its description,
    /// the conditions it is offered for (and where it is the default), its parameters, and a
    /// drawing of it on those conditions; plus one SVG per type.
    /// </summary>
    internal static class Catalogue
    {
        public static void Write(string folder, List<JointTypeInfo> types,
            Dictionary<string, List<(Case Case, bool Default)>> offered, List<Cell> cells,
            Dictionary<string, Dictionary<string, object>> defaults, List<Case> cases)
        {
            Directory.CreateDirectory(folder);

            var md = new StringBuilder();
            md.AppendLine("# Joint catalogue");
            md.AppendLine();
            md.AppendLine("Generated by GluLamb.Gallery from the joint registry: do not edit by hand. Each joint type is tried on the gallery's joint conditions, ");
            md.AppendLine("as drawn and with the beam sections turned a quarter turn, each with and without Flip. A cell passes when the joint builds, no two cut beams overlap, ");
            md.AppendLine("and every beam keeps its body. Beams are coloured by their order in the condition; hardware is grey.");
            md.AppendLine();
            md.AppendLine("| Type | Name | Conditions | Default for | Cells |");
            md.AppendLine("|---|---|---|---|---|");
            foreach (var type in types)
            {
                var mine = cells.Where(x => x.Type.Id == type.Id).ToList();
                var conditions = offered.TryGetValue(type.Id, out var list) ? list : new List<(Case Case, bool Default)>();
                var families = string.Join(", ", conditions.Select(x => x.Case.Family).Distinct());
                var defaultFor = string.Join(", ", conditions.Where(x => x.Default).Select(x => x.Case.Name));
                var result = mine.Count == 0 ? "not tried" : mine.All(x => x.Pass) ? $"{mine.Count} ok" : $"{mine.Count(x => !x.Pass)} of {mine.Count} fail";
                md.AppendLine($"| [`{type.Id}`](#{Anchor(type.Id)}) | {type.Name} | {families} | {defaultFor} | {result} |");
            }
            md.AppendLine();

            foreach (var type in types)
            {
                md.AppendLine($"## {type.Id}");
                md.AppendLine();
                md.AppendLine($"**{type.Name}.** {type.Attribute.Description}");
                md.AppendLine();
                var summary = Summary(type.Type);
                if (!string.IsNullOrEmpty(summary))
                {
                    md.AppendLine(summary);
                    md.AppendLine();
                }

                md.AppendLine($"Class `{type.Type.Name}`, {type.Attribute.Arity} part(s){(type.Attribute.Topology != JointTopology.Unknown ? $", {type.Attribute.Topology} topology" : "")}.");
                md.AppendLine();

                if (offered.TryGetValue(type.Id, out var list) && list.Count > 0)
                {
                    md.AppendLine("Offered for: " + string.Join(", ", list.Select(x => x.Default ? $"**{x.Case.Name}** (default)" : x.Case.Name)) + ".");
                    md.AppendLine();
                }
                else
                {
                    md.AppendLine("Not offered for any of the gallery's conditions.");
                    md.AppendLine();
                }

                defaults.TryGetValue(type.Id, out var values);
                var parameters = type.Parameters;
                if (parameters.Count > 0)
                {
                    md.AppendLine("| Parameter | Default | Unit | Description |");
                    md.AppendLine("|---|---|---|---|");
                    foreach (var p in parameters)
                    {
                        var attr = p.GetCustomAttribute<JointParameterAttribute>();
                        var value = values != null && values.TryGetValue(p.Name, out var v) ? Format.Value(v) : "";
                        if (attr?.Unit == "radians" && values != null && values.TryGetValue(p.Name, out var rad) && rad is double r)
                            value = $"{Rhino.RhinoMath.ToDegrees(r):0.##}°";
                        md.AppendLine($"| {p.Name} | {value} | {(attr?.Unit == "radians" ? "angle" : attr?.Unit)} | {attr?.Description?.Replace("|", "\\|")} |");
                    }
                    md.AppendLine();
                }

                var mine = cells.Where(x => x.Type.Id == type.Id).ToList();
                if (mine.Count > 0)
                {
                    var file = $"{type.Id}.svg";
                    File.WriteAllText(Path.Combine(folder, file), Drawing.Svg(mine));
                    md.AppendLine($"![{type.Name}]({file})");
                    md.AppendLine();

                    foreach (var fail in mine.Where(x => !x.Pass))
                        md.AppendLine($"- Fails on {fail.Case.Name}, {fail.Variant}: {string.Join("; ", fail.Problems)}");
                    var messages = mine.SelectMany(x => x.Messages).Distinct().ToList();
                    foreach (var m in messages)
                        md.AppendLine($"- Note: {m}");
                    if (mine.Any(x => !x.Pass) || messages.Count > 0) md.AppendLine();
                }
            }

            File.WriteAllText(Path.Combine(folder, "README.md"), md.ToString());
        }

        private static string Anchor(string id) => id.Replace(".", "").ToLowerInvariant();

        /// <summary>
        /// The class's XML doc summary, if the documentation file was built next to the assembly.
        /// </summary>
        private static string Summary(Type type)
        {
            try
            {
                var xml = Path.ChangeExtension(type.Assembly.Location, ".xml");
                if (!File.Exists(xml)) return null;
                var doc = System.Xml.Linq.XDocument.Load(xml);
                var member = doc.Descendants("member").FirstOrDefault(m => (string)m.Attribute("name") == $"T:{type.FullName}");
                var summary = member?.Element("summary");
                if (summary == null) return null;
                var text = string.Join(" ", summary.DescendantNodes().OfType<System.Xml.Linq.XText>().Select(t => t.Value.Trim()).Where(t => t.Length > 0));
                return text;
            }
            catch
            {
                return null;
            }
        }
    }
}
